services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1004
      - PGID=1004
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbittorrent:/config
      - /mnt/media/downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1004
      - PGID=1004
      - TZ=Europe/Paris
    volumes:
      - ./config/sonarr:/config
      - /mnt/media/tv:/tv
      - /mnt/media/downloads:/downloads
    ports:
      - "8989:8989"

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1004
      - PGID=1004
      - TZ=Europe/Paris
    volumes:
      - ./config/radarr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/downloads:/downloads
    ports:
      - "7878:7878"

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1004
      - PGID=1004
      - TZ=Europe/Paris
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - PUID=1004
      - PGID=1004
      - TZ=Europe/Paris
    volumes:
      - ./config/jellyseerr:/config
      - /mnt/media/movies:/movies
      - /mnt/media/tv:/tv
    ports:
      - "5055:5055"

networks:
  default:
    driver: bridge
